theme: jekyll-theme-minimal
title: Test site title <a href="https://hamaier.github.io/ak-dm-glossary">Home</a>
collections:
  glossary:
      output: true
      permalink: "/:collection/:path/"

markdown: kramdown

defaults:
    - scope:
      path: ""
      type: glossary
    values:
      layout: single
