# theme: jekyll-theme-minimal
# title: Test site title <a href="https://hamaier.github.io/ak-dm-glossary">Home</a>
collections:
  glossary:
    defaults:
      layout: post
    output: true
    permalink: "/:collection/:name/"
    ##      permalink: "/:collection/:path/"
